# Computation on NumPy Arrays: Universal Functions

In [2]:
import numpy as np

In [5]:
x = np.arange(5)
y = np.arange(1, 6)
print x
print y

[0 1 2 3 4]
[1 2 3 4 5]


In [10]:
print x + y
print x - y
print x*y
print x/y

[1 3 5 7 9]
[-1 -1 -1 -1 -1]
[ 0  2  6 12 20]
[0 0 0 0 0]


In [7]:
z = np.arange(9).reshape((3, 3))
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
2 ** z

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [9]:
z ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [11]:
x2 = [1,2,3,4,5]
[x + 5 for x in x2]

[6, 7, 8, 9, 10]

In [13]:
x = np.arange(4)
print x
print "x     =", x
print "x + 5 =", x + 5
print "x - 5 =", x - 5
print "x * 2 =", x * 2
print "x / 2 =", x / 2.0

[0 1 2 3]
x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]


In [14]:
print "-x     = ", -x
print "x ** 2 = ", x ** 2
print "x % 2  = ", x % 2

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [15]:
-((0.5*x + 1) ** 2)

array([-1.  , -2.25, -4.  , -6.25])

## Universal Functions

In [17]:
x = np.array([-2, -1, 0, 1, 2])

In [19]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [22]:
theta = np.linspace(0, np.pi, 6)

In [23]:
print "theta      = ", theta
print "sin(theta) = ", np.sin(theta)
print "cos(theta) = ", np.cos(theta)
print "tan(theta) = ", np.tan(theta)

theta      =  [ 0.          0.62831853  1.25663706  1.88495559  2.51327412  3.14159265]
sin(theta) =  [  0.00000000e+00   5.87785252e-01   9.51056516e-01   9.51056516e-01
   5.87785252e-01   1.22464680e-16]
cos(theta) =  [ 1.          0.80901699  0.30901699 -0.30901699 -0.80901699 -1.        ]
tan(theta) =  [  0.00000000e+00   7.26542528e-01   3.07768354e+00  -3.07768354e+00
  -7.26542528e-01  -1.22464680e-16]


In [27]:
x = np.linspace(1,5,5)
print "x     =", x 
print "e^x   =", np.exp(x) 
print "2^x   =", np.exp2(x)
print "3^x   =", np.power(3, x)
print "x^3   =", np.power(x, 3)

x     = [ 1.  2.  3.  4.  5.]
e^x   = [   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591 ]
2^x   = [  2.   4.   8.  16.  32.]
3^x   = [   3.    9.   27.   81.  243.]
x^3   = [   1.    8.   27.   64.  125.]


In [28]:
print "x        =", x
print "ln(x)    =", np.log(x)
print "log2(x)  =", np.log2(x)
print "log10(x) =", np.log10(x)

x        = [ 1.  2.  3.  4.  5.]
ln(x)    = [ 0.          0.69314718  1.09861229  1.38629436  1.60943791]
log2(x)  = [ 0.          1.          1.5849625   2.          2.32192809]
log10(x) = [ 0.          0.30103     0.47712125  0.60205999  0.69897   ]


Available ufuncs: https://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations