# The Basics of NumPy Arrays

In [1]:
distances = [10, 15, 17, 26]
times = [0.3, 0.47, 0.55, 1.20]

In [5]:
# Calculate velocities with Python
velocities = []
for i in range(4):
    velocities.append(distances[i]/times[i])

In [9]:
[d/t for d,t in zip(distances, times)]

[33.333333333333336,
 31.914893617021278,
 30.909090909090907,
 21.666666666666668]

In [11]:
import numpy as np

In [12]:
# Calculate velocities with Numpy
distance = np.array(distances)
time = np.array(times)
velocity = distance / time
velocity

array([ 33.33333333,  31.91489362,  30.90909091,  21.66666667])

In [13]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=10)  # 1D array
x2 = np.random.randint(10, size=(3, 4))  # 2D array
x3 = np.random.randint(10, size=(3, 4, 5))  # 3D array

In [14]:
x2

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9]])

In [20]:
x2.ndim

2

In [15]:
print "x3 ndim: ", x3.ndim
print "x3 shape:", x3.shape 
print "x3 size: ", x3.size

x3 ndim:  3
x3 shape: (3L, 4L, 5L)
x3 size:  60


In [21]:
print "dtype:", x3.dtype

dtype: int32


In [22]:
print "itemsize:", x3.itemsize, "bytes"
print "nbytes:", x3.nbytes, "bytes"

itemsize: 4 bytes
nbytes: 240 bytes


In [ ]:
x1

## Getting Elements from arrays

In [ ]:
x1[1]

In [ ]:
x1[4]

In [ ]:
x1[-1]

In [ ]:
x1[-2]

### Getting elements from a 2d-array (matrix)

In [ ]:
x2

In [ ]:
x2[2,0]

In [ ]:
## Setting elements
x2[0, 0] = 12
x2

In [ ]:
print x1
print x1.dtype

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

### Array Creation

In [23]:
# From lists
arr1 = np.array([1,2,5,3,5])
arr2d = np.array([
        [1,2],
        [2,3],
        [4,5]
    ])
print arr1
print arr2d

[1 2 5 3 5]
[[1 2]
 [2 3]
 [4 5]]


In [24]:
arr2d.shape

(3L, 2L)

In [25]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [26]:
#  Ones and zeros
ones3x4 = np.ones((3,4))
zeros3x4 = np.zeros((3,4))
print ones3x4
print ""
print zeros3x4

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [27]:
# Useful functions
print np.arange(50), '\n'
print np.arange(1,5,0.5), '\n'
print np.arange(100,1,-2), '\n'
print np.linspace(0,10,50), '\n'

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5] 

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2] 

[  0.           0.20408163   0.40816327   0.6122449    0.81632653
   1.02040816   1.2244898    1.42857143   1.63265306   1.83673469
   2.04081633   2.24489796   2.44897959   2.65306122   2.85714286
   3.06122449   3.26530612   3.46938776   3.67346939   3.87755102
   4.08163265   4.28571429   4.48979592   4.69387755   4.89795918
   5.10204082   5.30612245   5.51020408   5.71428571   5.91836735
   6.12244898   6.32653061   6.53061224   6.73469388   6.93877551
   7.14285714   7.34693878   7.55102041   7.75510204   7.95918367
   8.16326531   8.36734694   8.57142857   8.7755102    8.97959184
 

## Slicing

In [28]:
x = np.arange(1,5,0.5)
x

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [33]:
x[-2]

4.0

In [34]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [36]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [37]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [39]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [40]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [42]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

In [45]:
x2

array([[7, 6, 8, 8],
       [1, 6, 7, 7],
       [8, 1, 5, 9]])

In [48]:
x2[0,0] = -1

In [49]:
x2

array([[-1,  6,  8,  8],
       [ 1,  6,  7,  7],
       [ 8,  1,  5,  9]])

In [ ]:
print x2

In [ ]:
x2_sub = x2[:2, :2]
print x2_sub

## Reshaping Methods

In [52]:
x2 = np.arange(12)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
# Reshape
x2 = x2.reshape(2,6)
print x2

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
# Flatten 
x2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
# Concatenation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [57]:
y

array([[9, 8, 7],
       [6, 5, 4]])

In [58]:
# Stack arrays
x = np.array([1, 2, 3])
y = np.array([[9, 8, 7], [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, y])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [59]:
# horizontally stack the arrays
np.hstack([y[0,:], x])

array([9, 8, 7, 1, 2, 3])

In [60]:
x = np.arange(10)

In [61]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x[0] = 3.1561548

In [63]:
x

array([3, 1, 2, 3, 4, 5, 6, 7, 8, 9])