# Aggregations

In [2]:
import numpy as np

In [4]:
np.random.seed(1)

In [5]:
x = np.random.randint(0,9,10)
x

array([5, 8, 5, 0, 0, 1, 7, 6, 2, 4])

In [9]:
x.mean()

3.7999999999999998

In [8]:
print x.std()
print x.min()
print x.max()

2.74954541697
0
8


In [10]:
M = np.random.randint(0,9,size=(3,5))
M

array([[5, 2, 4, 2, 4],
       [7, 7, 1, 7, 0],
       [6, 7, 6, 1, 0]])

In [11]:
print M.min()
print M.max()
print M.mean()

0
7
3.93333333333


In [12]:
M

array([[5, 2, 4, 2, 4],
       [7, 7, 1, 7, 0],
       [6, 7, 6, 1, 0]])

In [14]:
print M.min(axis=1) # max of columns
#print M.min(axis=1) # min of rows

[2 0 0]


In [20]:
M.mean(axis=0)

array([ 6.        ,  5.33333333,  3.66666667,  3.33333333,  1.33333333])