# Aggregations

In [1]:
import numpy as np

In [2]:
np.random.seed(1)

In [3]:
M = np.random.randint(0,9,size=(3,5))
M

array([[5, 8, 5, 0, 0],
       [1, 7, 6, 2, 4],
       [5, 2, 4, 2, 4]])

In [4]:
np.sin(M)

array([[-0.95892427,  0.98935825, -0.95892427,  0.        ,  0.        ],
       [ 0.84147098,  0.6569866 , -0.2794155 ,  0.90929743, -0.7568025 ],
       [-0.95892427,  0.90929743, -0.7568025 ,  0.90929743, -0.7568025 ]])

In [5]:
print M.min()
print M.max()
print M.mean()

0
8
3.66666666667


In [9]:
M

array([[5, 8, 5, 0, 0],
       [1, 7, 6, 2, 4],
       [5, 2, 4, 2, 4]])

In [6]:
print M.min(axis=0) # max of columns
print M.min(axis=1) # min of rows

[1 2 4 0 0]
[0 1 2]


In [1]:
M.std(axis=1)

NameError: name 'M' is not defined