# Comparisons, Masks, and Boolean Logic

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x < 3  # less than

array([ True,  True, False, False, False], dtype=bool)

In [4]:
x > 3  # greater than

array([False, False, False,  True,  True], dtype=bool)

In [5]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False], dtype=bool)

In [6]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True], dtype=bool)

In [7]:
x != 3  # not equal

array([ True,  True, False,  True,  True], dtype=bool)

In [8]:
x == 3  # equal

array([False, False,  True, False, False], dtype=bool)

In [9]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False], dtype=bool)

In [10]:
x = np.random.randint(0,10, size=(3, 4))
x

array([[6, 9, 7, 3],
       [5, 8, 9, 3],
       [4, 5, 2, 2]])

In [11]:
x < 6

array([[False, False, False,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [ ]:
# how many values less than six?
np.count_nonzero(x < 6)

In [13]:
np.sum(x < 6)

7

In [15]:
# how many values less than six in each row?
(x < 6).sum(axis=1)

array([1, 2, 4])

In [16]:
# are there any values greater than eight?
np.any(x > 8)

True

In [17]:
# are there any values less than zero?
np.any(x < 0)

False

In [18]:
# are all values less than ten?
np.all(x < 10)

True

In [19]:
# are all values less than 8?
np.all(x < 8)

False

In [20]:
# are all values equal to six?
np.all(x == 6)

False

In [ ]:
# are all values in each row less than four?
np.all(x < 4, axis=1)

In [ ]:
x

In [ ]:
x < 5

### Boolean mask

In [33]:
x = np.random.randint(0,10,10)

In [34]:
x

array([0, 3, 9, 1, 7, 5, 0, 7, 1, 0])

In [25]:
x >= 5

array([False,  True,  True, False, False,  True,  True, False,  True,
       False,  True,  True,  True,  True, False], dtype=bool)

In [26]:
x[x >= 5]

array([6, 7, 7, 8, 9, 8, 9, 6, 9])

In [29]:
x[x > 0]

array([9, 3, 4, 3, 4, 4, 5, 6, 9])

In [30]:
(x >= 2)

array([ True,  True, False,  True, False, False, False,  True,  True,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False], dtype=bool)

In [35]:
(x >= 2)

array([False,  True,  True, False,  True,  True, False,  True, False, False], dtype=bool)

In [36]:
(x <= 6)

array([ True,  True, False,  True, False,  True,  True, False,  True,  True], dtype=bool)

In [37]:
(x >= 2) & (x <= 6) # bitwise logical and

array([False,  True, False, False, False,  True, False, False, False, False], dtype=bool)

In [38]:
x[(x >= 2) & (x <= 6)]

array([3, 5])

In [41]:
x[x > 1.5*x.mean()]

array([9, 7, 5, 7])

## Fancy indexing

In [42]:
x = np.random.randint(100, size=10)
x

array([32, 31, 29, 34, 24, 73, 65, 62, 36, 90])

In [43]:
x[[0,2,7]]

array([32, 29, 62])

In [44]:
x = np.random.randint(0,100, size=(5,10))
x

array([[92, 92, 17, 22,  9, 63,  4, 79, 87, 18],
       [90, 43, 15, 66, 75,  7, 86, 16, 89, 97],
       [81, 20, 60, 89, 60, 24, 70, 38, 59, 20],
       [70, 40, 81, 48, 14, 22, 76, 62, 75, 94],
       [63, 89, 55, 86, 65, 85, 34, 13,  3, 10]])

In [48]:
## Try to get separated elemens from the array
x[:,0:2]

array([[92, 92],
       [90, 43],
       [81, 20],
       [70, 40],
       [63, 89]])