# Numpy Exercises

In [1]:
import numpy as np

#### Print the numpy version

In [2]:
np.__version__

'1.10.4'

#### Create the following vectors

In [5]:
# A vector of zeros of size 10 but the fifth value equal to 1
x = np.zeros(10)
x[4] = 1
print(x)

# A vector with values ranging from 1 to 50
print np.arange(1,50)

# A vector with the integer multiples of 5 less than 100
print np.arange(0,100,5)

# Reverse the vector reciently created (first element becomes last)
print np.arange(0,100,5)[::-1]

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[95 90 85 80 75 70 65 60 55 50 45 40 35 30 25 20 15 10  5  0]


#### Create a 3x3 matrix with values ranging from 1 to 9

In [10]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.random.randint(1,10,size=(3,3))

array([[9, 1, 7],
       [7, 9, 4],
       [3, 1, 9]])

#### Find indices of non-zero elements from ``[1,2,0,0,4,0]``

In [13]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [28]:
x == 0

array([False, False, False, False, False,  True, False, False, False, False], dtype=bool)

In [15]:
np.where(x == 0)

(array([2, 3, 5], dtype=int64),)

In [17]:
x[x > 0]

array([1, 2, 4])

#### Create a 10x10 array with random integers from 0 to 99. Find the minimum and maximum values

In [19]:
rand_array = np.random.randint(0,100, size=(10,10))
rand_array

array([[50, 67, 63, 23, 99, 63, 30, 64, 28, 93],
       [20, 78, 26, 71, 80,  3, 59, 75, 48,  3],
       [73,  3, 10, 10, 72, 73, 15, 30, 65, 96],
       [47, 19, 33, 27, 28, 56,  5, 10, 64, 59],
       [91, 31, 31, 33,  1, 15, 57, 12, 95, 90],
       [85, 27, 66, 23, 96, 31, 38, 16, 23, 83],
       [83, 29, 69, 63, 45, 70, 91, 35, 43, 74],
       [33, 21, 13, 84, 17, 30,  8, 80, 20, 61],
       [18, 78, 81, 10,  1, 69, 71, 59, 73, 73],
       [95, 43, 75, 47, 14, 93, 61, 64, 32, 15]])

In [20]:
print rand_array.min()
print rand_array.max()

1
99


#### Create a random vector of size 30 and find the mean and the standard deviation

In [22]:
rand2 = np.random.random(30)
print rand2.mean()
print rand2.std()

0.530294747203
0.277298730476


#### Create random vector of size 10 and replace the maximum value with 0

In [27]:
x = np.random.randint(0,21,10)
x

array([17,  7,  3, 12,  2,  0,  1,  1,  6, 14])

In [26]:
x[x.argmax()] = 0
x

array([ 1, 13, 13,  8,  9,  0, 14, 19, 15,  1])

#### Create two arrays of size 10 with random integers between 1 and 20. Find common numbers between two arrays.

#### Create a 3 x 5 matrix of random integers from 0 to 9, find the sums of the rows, the columns and the whole matrix

#### Calculate the values of the function $f(x) = x^2 + 3x - 6$ for 100 numbers in from -2 to 2

In [29]:
x = np.linspace(-2, 2, 100)
f = x**2 + 3*x - 6
f

array([-8.        , -8.03877155, -8.07427813, -8.10651974, -8.13549638,
       -8.16120804, -8.18365473, -8.20283645, -8.21875319, -8.23140496,
       -8.24079176, -8.24691358, -8.24977043, -8.24936231, -8.24568922,
       -8.23875115, -8.22854811, -8.21508009, -8.19834711, -8.17834915,
       -8.15508622, -8.12855831, -8.09876543, -8.06570758, -8.02938476,
       -7.98979696, -7.94694419, -7.90082645, -7.85144373, -7.79879604,
       -7.74288338, -7.68370574, -7.62126314, -7.55555556, -7.486583  ,
       -7.41434547, -7.33884298, -7.2600755 , -7.17804306, -7.09274564,
       -7.00418325, -6.91235588, -6.81726354, -6.71890623, -6.61728395,
       -6.51239669, -6.40424446, -6.29282726, -6.17814509, -6.06019794,
       -5.93898582, -5.81450872, -5.68676666, -5.55575962, -5.4214876 ,
       -5.28395062, -5.14314866, -4.99908173, -4.85174982, -4.70115294,
       -4.54729109, -4.39016427, -4.22977247, -4.0661157 , -3.89919396,
       -3.72900724, -3.55555556, -3.37883889, -3.19885726, -3.01

#### Implement the following algorithm in a function to detect outliers:
1. Calculate the first and third quartiles $Q_1, Q_3$ of a vector.
1. Calculate the inter-quartile range (IQR) of a vector.
2. Categorize as outliers any value outside the intervar $[Q_1 - 1.5IQR, Q_3 + 1.5IQR]$

In [49]:
x = np.random.randint(0,10,100)

In [50]:
## Q1: Number in the vector such that 25% of the values in the vector are equal 
# o less than that number: np.percentile

## Q3: Number in the vector such that 75% of the values in the vector are equal 
# o less than that number: np.percentile

## IQR = Q3 - Q1

def detect_outliers(vector):
    Q1 = np.percentile(vector, q=25)
    Q3 = np.percentile(vector, q=75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    mask = (vector > upper) | (vector < lower)
    return vector[mask]

In [61]:
x = np.random.normal(100, 10, (10,10))
#x

In [54]:
x[0] = 100
x[5] = 200
x[9] = 150

In [55]:
detect_outliers(x)

array([100, 200, 150])

#### Using the same algorithm as before, implement a function that replaces all the outliers with the appropiate endpoint of the given interval (for small outliers use the left endpoint and for large outliers the right one)

#### Create a 2d array of shape (10,10) with 1 on the border and 0 inside

#### Using the standard normal distribution create a random vector of size 100. Find the closest value to 1

In [65]:
z = np.random.normal(size = 100)
index_closest1 = (np.abs(z - 1)).argmin()
z[index_closest1]

1.0150403896469427

#### Repeate the same excersise as above but this time create a 100 x 10 matrix. Find the closest value to 1 in every column.

#### Create an array of 100 integers from 0 to 9. Find the most and the least frequent values in the array.

#### Simulate tossing a fair coin 20 times, count the number of "heads".

#### As in the last exercise, simulate tossing a fair coin 20 times, do the same simulation 1,000 times. Count the number of "heads" for each simulation (save them in an array counts). Report and give an interpretation of the descriptive statistics of counts. Print the distribution of counts